name:                pet
version:             0.1.0.0
github:              "eanea/haskell-pet"
license:             BSD3
author:              "eanea"
maintainer:          "example@example.com"
copyright:           "2022 eanea"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/eanea/haskell-pet#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- lens  
- servant-server
- servant-docs
- wai
- warp
- text
- bytestring
- http-types
- persistent
- persistent-postgresql
- monad-logger
- unliftio-core
- resource-pool
- mtl
- say
- safe
- safe-exceptions
- servant-swagger
- servant-swagger-ui
- servant-swagger-ui-core
- swagger2
- containers
- servant-auth
- servant-auth-server
- servant-auth-swagger

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  pet-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - pet

tests:
  pet-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - pet
    - hspec
    - hspec-wai
    - hspec-wai-json
    - aeson
